CUDA_VISIBLE_DEVICES=1 python3 augment_videos_FOMM.py --config ./config/vox-adv-256.yaml --checkpoint /playpen-nas-ssd/data/shared_checkpoints/FOMM/vox-adv-cpk.pth.tar --source_path /playpen-nas-hdd/UNC_Google_Physio/UBFC-rPPG/DATASET_2_backup/DATASET_2/train/pool1 --driving_path /playpen-nas-ssd/data/datasets/TalkingHead-1KH/train/new_categories/all_hp_pool/new_hp_intense_picked --augmented_path /playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/MAUBFC_LARGE_HP_PICKED_FOMM --relative --adapt_scale --dataset UBFC-rPPG &
sleep 4m
CUDA_VISIBLE_DEVICES=2 python3 augment_videos_FOMM.py --config ./config/vox-adv-256.yaml --checkpoint /playpen-nas-ssd/data/shared_checkpoints/FOMM/vox-adv-cpk.pth.tar --source_path /playpen-nas-hdd/UNC_Google_Physio/UBFC-rPPG/DATASET_2_backup/DATASET_2/train/pool2 --driving_path /playpen-nas-ssd/data/datasets/TalkingHead-1KH/train/new_categories/all_hp_pool/new_hp_intense_picked --augmented_path /playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/MAUBFC_LARGE_HP_PICKED_FOMM --relative --adapt_scale --dataset UBFC-rPPG &
sleep 4m
CUDA_VISIBLE_DEVICES=3 python3 augment_videos_FOMM.py --config ./config/vox-adv-256.yaml --checkpoint /playpen-nas-ssd/data/shared_checkpoints/FOMM/vox-adv-cpk.pth.tar --source_path /playpen-nas-hdd/UNC_Google_Physio/UBFC-rPPG/DATASET_2_backup/DATASET_2/train/pool3 --driving_path /playpen-nas-ssd/data/datasets/TalkingHead-1KH/train/new_categories/all_hp_pool/new_hp_intense_picked --augmented_path /playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/MAUBFC_LARGE_HP_PICKED_FOMM --relative --adapt_scale --dataset UBFC-rPPG &
sleep 4m
CUDA_VISIBLE_DEVICES=4 python3 augment_videos_FOMM.py --config ./config/vox-adv-256.yaml --checkpoint /playpen-nas-ssd/data/shared_checkpoints/FOMM/vox-adv-cpk.pth.tar --source_path /playpen-nas-hdd/UNC_Google_Physio/UBFC-rPPG/DATASET_2_backup/DATASET_2/train/pool4 --driving_path /playpen-nas-ssd/data/datasets/TalkingHead-1KH/train/new_categories/all_hp_pool/new_hp_intense_picked --augmented_path /playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/MAUBFC_LARGE_HP_PICKED_FOMM --relative --adapt_scale --dataset UBFC-rPPG &
sleep 4m
CUDA_VISIBLE_DEVICES=5 python3 augment_videos_FOMM.py --config ./config/vox-adv-256.yaml --checkpoint /playpen-nas-ssd/data/shared_checkpoints/FOMM/vox-adv-cpk.pth.tar --source_path /playpen-nas-hdd/UNC_Google_Physio/UBFC-rPPG/DATASET_2_backup/DATASET_2/train/pool5 --driving_path /playpen-nas-ssd/data/datasets/TalkingHead-1KH/train/new_categories/all_hp_pool/new_hp_intense_picked --augmented_path /playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/MAUBFC_LARGE_HP_PICKED_FOMM --relative --adapt_scale --dataset UBFC-rPPG &
sleep 2m

wait